version: '3.0' 

services:
  client-game:
    container_name: ${GAME_CLIENT_CONTAINER_NAME}
    image: ${GAME_CLIENT_CONTAINER_NAME}
    build: 
      context: ${WORKING_DIR}
      dockerfile: docker-threejs-sandbox/Dockerfile
    restart: "no"
    network_mode: "bridge"
    volumes:
      - project-volume:/projects/threejs-sandbox
    command: [ "./three-client/_install.sh" ]
    
volumes:
  project-volume:
    external: true
    name: ${VOLUME_NAME}